name: build
on:
  pull_request:
  push:
    branches: [ rolling ]
  workflow_dispatch:
defaults:
  run:
    shell: bash
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        distro: ['iron', 'jazzy', 'rolling']
    container:
      image: ros:${{ matrix.distro }}-ros-base
    timeout-minutes: 30
    steps:
    - name: Deps
      run: |
        apt update && apt install -y curl
    - uses: actions/checkout@v4
    - name: rosdep
      run: |
        rosdep update
        rosdep install --from-paths . -yir
    - name: build
      run: /ros_entrypoint.sh colcon build
